### ISSUE TITLE
Check uniqueness of Command, Query and Event names

### ISSUE THREAD

**Issue by shochdoerfer** [event-engine/php-engine#11]
When adding commands, queries or events to the event engine, it is checked if the name that should be registered is already registered. That check only happens in the same "space", meaning I could potentially register a command and an event with the same name. In the Swagger file generation the uniqueness is also not checked, meaning one will overwrite the other. Took me quite a while to figure that out. An additional check would help here a lot.

Happy to provide a PR if this makes sense for you :)

**Comment by codeliner** [comment]
PR would be great :+1:

**Comment by shochdoerfer** [comment]
Will see what I can do!

**Comment by codeliner** [comment]
You can add the checks here: https://github.com/event-engine/php-engine/blob/master/src/EventEngine.php#L428-L473

Would be nice to throw verbose exceptions like "Command name ${$commandName} already used as event name. You should check your naming strategy!"
