### ISSUE TITLE
EventEngine::rebuildAggregateState does not work as expected with MultiModelStore

### ISSUE THREAD

**Issue by sandrokeil** [event-engine/php-engine#13]
If a MultiModelStore is configured, `rebuildAggregateState` uses last document state for rebuild. It's a problem of [`\EventEngine\Aggregate\GenericAggregateRepository::getAggregateRoot`](https://github.com/event-engine/php-engine/blob/master/src/Aggregate/GenericAggregateRepository.php#L147-L155).

The expected behavior is to replay all events. The document store state should not be considered.

**Comment by codeliner** [comment]
Closed by #14
