### ISSUE TITLE
Using the specification pattern in combination with Event Engine

### ISSUE THREAD

**Issue by arnedesmedt** [event-engine/php-engine#20]
Hi,

Previously I used the [specification pattern](https://en.wikipedia.org/wiki/Specification_pattern) in the prooph EventSorucing library. Their were no troubles because the state was immediately changed after the events were recorded (via the apply function):

```php
 /**
     * Record an aggregate changed event
     */
    protected function recordThat(AggregateChanged $event): void
    {
        $this->version += 1;

        $this->recordedEvents[] = $event->withVersion($this->version);

        $this->apply($event);
    }
```
So i could send the aggregate root object to a specification and check if the state will met the condition.

In Event engine I used a context provider that will generate the specification, so the specification is send to the second parameter in my aggregate method.

But the problem is that the state is not updated in this method because the apply method is not  called after that the events are recorded.

```php
public function recordThat(DomainEvent $event) : void
    {
        $this->recordedEvents[] = $event;
    }
```

The state is only changed in the apply method, But is there a proper way of accessing my Specification object in the apply methods?

Or do I have to configure my oop port so I can send the specification object via the port?

Thx in advance!

Greetings,
Arne

**Comment by codeliner** [comment]
Ok, let's see if I understand your question:

You first want to change the state of the aggregate by recording an event and then test the new state against a specification?

Can you give me a real world example?

The thing is, an aggregate should only record an event if everything is fine. Doing the validation after event recording sounds like a modeling issue.This also means that NO validation should take place in apply functions. Once an event is recorded, it is written in stone. The aggregate has to change state according to the event, no matter what.

Anyway, if you really want to change state before passing it to the specification (so basically validate a future state), you should modify a local copy of the state and pass the temporary modified state to the specification. If you use a single state property in your aggregates and this state property is an immutable data structure, changing a local copy in a handle function should be doable.

But again, I'd be interested in a real world example to see if this can be designed in a different way.

**Comment by arnedesmedt** [comment]
Previously we did something like this in the event sourcing library:

```php
public function addVhost(
        VhostUuid $vhostUuid,
        VhostName $name,
        VhostAliases $aliases,
        VhostPort $port,
        VhostWebroot $webroot,
        AbstractSpecification $specification
    ) : self {
        $this->recordThat(
            VhostAdded::fromData(
                $this->aggregateId(),
                $vhostUuid,
                $name,
                $aliases,
                $port,
                $webroot
            )
        );

        $this->checkVhost($vhostUuid, $specification);

        return $this;
    }

private function checkVhost(VhostUuid $vhostUuid, AbstractSpecification $specification) : void
    {
        /** @var stdClass|null $vhost */
        $vhost = $this->vhost($vhostUuid);

        if (! $specification->isSatisfiedBy($vhost)) {
            throw $specification->notSatisfiedException();
        }
    }
```

CheckVhost throws an exception if the specification is not met. And because of that the events are not written to the database (but yes, they are already applied in the code, and now I know, that's wrong)

Could it be that the specification pattern is not a good way to check business logic in the aggregate? Because of the state that isn't applied when you need to check the constraints.

Do you use specific design patterns to execute some business logic?

Thx in advance!

Arne

**Comment by arnedesmedt** [comment]
Thx for the answer! It's indeed a better solution to create the vhost manually instead of using event engine for it.
