### ISSUE TITLE
Describe differences between original project and fork

### ISSUE THREAD

**Issue by uniconstructor** [event-engine/php-engine#22]
Because this project has no usual github link ("frorked from ...") to original Event Machine repository (https://github.com/proophsoftware/event-machine) it's hard to understand a difference.

Can you add link to original project to your readme?

**Comment by codeliner** [comment]
Hey @uniconstructor ,

thank you for the hint. I've added a section in the readme: https://github.com/event-engine/php-engine/blob/master/README.md#supersedes-event-machine
