### ISSUE TITLE
Cannot rewind a generator that was already run

### ISSUE THREAD

**Issue by arnedesmedt** [event-engine/php-engine#6]
Hi,

Thx for the new event machine v2!

I was implementing the event engine tutorial (https://event-engine.io/tutorial/) but I'm stuck on an exception thrown in the postgresql event store: It throws 'Cannot rewind a generator that was already run': https://github.com/prooph/pdo-event-store/blob/master/src/PostgresEventStore.php#L194-L200

The error is thrown at line 200. But the problem is that the iterator (here the Generator) is looped in the prepareData function and rewinded in the \iterator_count function. And that throws the exception. See https://www.php.net/manual/en/generator.rewind.php

Is there a workaround for preventing this error?

Thx in advance,

Arne

**Comment by codeliner** [comment]
Hey @arnedesmedt , thx for reporting the bug. It's my fault. I've tried to fix an issue with the [MapIterator](https://github.com/event-engine/php-engine-utils/blob/master/src/MapIterator.php) or the php-engine-utils package. We recognized a problem when using the MapIterator with a MongoDB cursor, so I've refactored it to use a Generator internally. Unfortunately, I've forgotten that Generators are not rewindable :( 

In our current project we use Event Engine with a custom MongoDB store (not open source yet) and the fix worked for us but I did not test it with prooph v7 PDO Event Store :(

## Fix

Run `composer update`. It should install the new [php-engine-utils release v0.1.4](https://github.com/event-engine/php-engine-utils/releases/tag/v0.1.4).

Can you try again with the new version?

*Sorry for the problems. I already discussed with @sandrokeil that we will write a test suite that goes through the tutorial and ensures it's working when we release a new version of a package.*

**Comment by arnedesmedt** [comment]
Thank you very much for the fix. It works now!

**Comment by codeliner** [comment]
great! Hopefully you can enjoy the rest of the tutorial without strange bugs ;)
